remove del from queue (#417)
When using the queue remotely, you get the error below. 
```
Exception ignored in: <function SimpleQueue.__del__ at 0x104d55f80>
Traceback (most recent call last):
  File "/Users/minzi/Dev/beam/examples/.venv/lib/python3.12/site-packages/beta9/abstractions/queue.py", line 74, in __del__
AttributeError: 'super' object has no attribute '__del__'
```
I dont think the `__del__` method is needed and it causes this problem
so I have removed it. There is no `__del__` on the `BaseAbstraction`.